### ISSUE TITLE
Project Checkpoint #3 - Aiden Huynh, 5/20 (imported)

### ISSUE THREAD

**Issue by aidenhuynh** [John-sCC/jcc_frontend#111]
## Brief Description

Our team made too many features that all kind of suck so the goal for the final sprint is to POLISH POLISH POLISH!!!

My main goal will be providing wireframes and designing frontend for our team, as a good UI is something that I feel like a lot of projects lack and it will give us a feeling of professionalism, maybe allowing our project to be used in the future.

Emphasis on styling will be important for others in our team as well, as they need assets to use for the SASS lessons.

## Wireframes

So far, I have completed two of our most important wireframes, the dashboard, where students will see their grades, assignments, and classes, and the inbox page for messaging other students and teachers.

> all wireframes [here](https://docs.google.com/presentation/d/1DYGLNGXvdMkkJJSRu71eUlVI5elo95R_dUn3O1zLDcs/edit?usp=sharing)

### Dashboard

This is the most important page, and I'm currently working on converting it to real html and css. Implementation will either be done by me or Drew.

![Screen Shot 2024-05-20 at 11 10 20 PM](https://github.com/aidenhuynh/Epic_CSA/assets/112529809/985ff5ea-dd64-4eac-a912-e72afa3f2caf)

Here's what I have for the html/css part, should be **done by tomorrow (Wednesday)**.

![Screen Shot 2024-05-20 at 11 17 13 PM](https://github.com/aidenhuynh/Epic_CSA/assets/112529809/d90e888b-e505-4259-8ca6-5b22dfc7e3ee)

I'm currently trying to figure out how to color the squares differently using scss lists so I can provide it as an example in our SASS lessons:

```scss
&:not(:only-of-type) {
    $default-colors: #ea9999ff #f9cc9dff #f9cc9dff #b6d8a9ff #a2c4c9ff #a5c2f4ff #a0c5e8ff #b4a7d7ff #d5a7bdff #ccccccff;

    @each $color in $default-colors {
        &:nth-child(#{index($default-colors, $color)}) {
            background-color: $color;
        }
    }
    
    &:hover {
        cursor: pointer;
    }
}
```

### Inbox

![Screen Shot 2024-05-20 at 11 11 31 PM](https://github.com/aidenhuynh/Epic_CSA/assets/112529809/cbf28c49-79cb-4cc2-8658-f4efc4d84759)

This page is being converted by Edwin and Ryan.

### Other:

- [x] Assignment creation
- [ ] Class period creation
- [ ] Resume builder
- [ ] Career search
- [x] QR Code generator

These will all be done by thursday

## Week Timeline:

Tue - Do remaining wireframes 1-3, send to members
Wed - Finish ALL wireframes and send out to members for implementation
Thurs - Fully integrate dashboard script into new HTML/CSS (MOST IMPORTANT FEATURE)
Fri - Team meeting/polish anything that needs to be polished
